/**:
  ros__parameters:
    # vehicle parameters
    vehicle_width: 0.5
    vehicle_length: 0.5
    vehicle_height: 2.0
    outside_lane_threshold_sec: 3.0

    # save settings
    save_to_csv: true
    save_file_name: "/tmp/test.csv"

    # Determine how to get vehicle self pose 
    # if use_odom is true, the vehicle pose will be get from odom topic
    # if use_odom is false, the vehicle pose will be get from pose topic
    use_odom: true